import type { Metadata } from "next";
import { Silkscreen } from 'next/font/google';
import { IBM_Plex_Sans } from 'next/font/google';

import './globals.css';
import NavBar from "./components/NavBar/NavBar";
import Footer from "./components/GlobalComponents/Footer/Footer";
import AboveFooterDownload from "./components/GlobalComponents/Footer/AboveFooterDownload";

// Initialize Silkscreen font
const silkscreenInit = Silkscreen({
  subsets: ['latin'],
  weight: ['400', '700'], // Silkscreen doesn't support 100/300 weights, so adjust accordingly
  variable: '--font-silkscreen', // Change the variable name to reflect Silkscreen
});

// Initialize IBM Plex Sans
const ibmPlexSansInit = IBM_Plex_Sans({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-ibm-plex',
});

export const metadata: Metadata = {
  title: "SamSoftwares",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${ibmPlexSansInit.variable} ${ibmPlexSansInit.variable}`}>
        <NavBar />
        {children}
        <AboveFooterDownload/>
        <Footer/>

      </body>

    </html>
  );
}
